/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubscriptionPlan = IDL.Variant({
  'monthly' : IDL.Null,
  'yearly' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PremiumSource = IDL.Variant({
  'stripe' : IDL.Null,
  'referral' : IDL.Null,
  'none' : IDL.Null,
  'manual' : IDL.Null,
});
export const Time = IDL.Int;
export const SubscriptionStatus = IDL.Record({
  'expiresAt' : Time,
  'plan' : SubscriptionPlan,
  'stripeSessionId' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const SportsCategory = IDL.Variant({
  'mlb' : IDL.Null,
  'nba' : IDL.Null,
  'nfl' : IDL.Null,
  'nhl' : IDL.Null,
  'soccer' : IDL.Null,
  'other' : IDL.Text,
  'ncaabb' : IDL.Null,
  'ncaaf' : IDL.Null,
});
export const BettingMarket = IDL.Variant({
  'sameGameParlays' : IDL.Null,
  'overUnder' : IDL.Null,
  'alternativeSpreads' : IDL.Null,
  'pointSpreads' : IDL.Null,
  'moneyLine' : IDL.Null,
  'otherMarkets' : IDL.Text,
  'alternativeOvers' : IDL.Null,
});
export const Prediction = IDL.Record({
  'id' : IDL.Text,
  'winningProbability' : IDL.Float64,
  'marketValue' : IDL.Text,
  'createdAt' : Time,
  'juice' : IDL.Text,
  'sport' : SportsCategory,
  'market' : BettingMarket,
  'matchDate' : Time,
});
export const ReferralCodeStatus = IDL.Record({
  'code' : IDL.Text,
  'validUntil' : Time,
});
export const ReferralStatus = IDL.Record({
  'expiresAt' : Time,
  'code' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'hasManualPremium' : IDL.Bool,
  'referral' : IDL.Opt(ReferralStatus),
  'subscription' : IDL.Opt(SubscriptionStatus),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateSubscription' : IDL.Func([IDL.Text, SubscriptionPlan], [], []),
  'addUpcomingMatch' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkPremiumStatus' : IDL.Func([], [PremiumSource], ['query']),
  'checkSubscriptionStatus' : IDL.Func(
      [],
      [IDL.Opt(SubscriptionStatus)],
      ['query'],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPrediction' : IDL.Func([Prediction], [], []),
  'createReferralCode' : IDL.Func([IDL.Text, Time], [], []),
  'deletePrediction' : IDL.Func([IDL.Text], [], []),
  'getActiveReferralCodes' : IDL.Func(
      [],
      [IDL.Vec(ReferralCodeStatus)],
      ['query'],
    ),
  'getAllPredictions' : IDL.Func([], [IDL.Vec(Prediction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoachingStyle' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getDepthChart' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getInjuryReport' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getNewsFlag' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getPrediction' : IDL.Func([IDL.Text], [IDL.Opt(Prediction)], ['query']),
  'getPredictionsByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(Prediction)],
      ['query'],
    ),
  'getPredictionsByMarket' : IDL.Func(
      [BettingMarket],
      [IDL.Vec(Prediction)],
      ['query'],
    ),
  'getPredictionsBySport' : IDL.Func(
      [SportsCategory],
      [IDL.Vec(Prediction)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUpcomingMatches' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantManualPremiumAccess' : IDL.Func([IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'redeemReferralCode' : IDL.Func([IDL.Text], [], []),
  'removeUpcomingMatch' : IDL.Func([IDL.Text], [], []),
  'revokeManualPremiumAccess' : IDL.Func([IDL.Principal], [], []),
  'revokeReferralCode' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCoachingStyle' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setDepthChart' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setInjuryReport' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setNewsFlag' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePrediction' : IDL.Func([Prediction], [], []),
  'updateUserProfileData' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubscriptionPlan = IDL.Variant({
    'monthly' : IDL.Null,
    'yearly' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PremiumSource = IDL.Variant({
    'stripe' : IDL.Null,
    'referral' : IDL.Null,
    'none' : IDL.Null,
    'manual' : IDL.Null,
  });
  const Time = IDL.Int;
  const SubscriptionStatus = IDL.Record({
    'expiresAt' : Time,
    'plan' : SubscriptionPlan,
    'stripeSessionId' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const SportsCategory = IDL.Variant({
    'mlb' : IDL.Null,
    'nba' : IDL.Null,
    'nfl' : IDL.Null,
    'nhl' : IDL.Null,
    'soccer' : IDL.Null,
    'other' : IDL.Text,
    'ncaabb' : IDL.Null,
    'ncaaf' : IDL.Null,
  });
  const BettingMarket = IDL.Variant({
    'sameGameParlays' : IDL.Null,
    'overUnder' : IDL.Null,
    'alternativeSpreads' : IDL.Null,
    'pointSpreads' : IDL.Null,
    'moneyLine' : IDL.Null,
    'otherMarkets' : IDL.Text,
    'alternativeOvers' : IDL.Null,
  });
  const Prediction = IDL.Record({
    'id' : IDL.Text,
    'winningProbability' : IDL.Float64,
    'marketValue' : IDL.Text,
    'createdAt' : Time,
    'juice' : IDL.Text,
    'sport' : SportsCategory,
    'market' : BettingMarket,
    'matchDate' : Time,
  });
  const ReferralCodeStatus = IDL.Record({
    'code' : IDL.Text,
    'validUntil' : Time,
  });
  const ReferralStatus = IDL.Record({ 'expiresAt' : Time, 'code' : IDL.Text });
  const UserProfile = IDL.Record({
    'hasManualPremium' : IDL.Bool,
    'referral' : IDL.Opt(ReferralStatus),
    'subscription' : IDL.Opt(SubscriptionStatus),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateSubscription' : IDL.Func([IDL.Text, SubscriptionPlan], [], []),
    'addUpcomingMatch' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkPremiumStatus' : IDL.Func([], [PremiumSource], ['query']),
    'checkSubscriptionStatus' : IDL.Func(
        [],
        [IDL.Opt(SubscriptionStatus)],
        ['query'],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPrediction' : IDL.Func([Prediction], [], []),
    'createReferralCode' : IDL.Func([IDL.Text, Time], [], []),
    'deletePrediction' : IDL.Func([IDL.Text], [], []),
    'getActiveReferralCodes' : IDL.Func(
        [],
        [IDL.Vec(ReferralCodeStatus)],
        ['query'],
      ),
    'getAllPredictions' : IDL.Func([], [IDL.Vec(Prediction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoachingStyle' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getDepthChart' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getInjuryReport' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getNewsFlag' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getPrediction' : IDL.Func([IDL.Text], [IDL.Opt(Prediction)], ['query']),
    'getPredictionsByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(Prediction)],
        ['query'],
      ),
    'getPredictionsByMarket' : IDL.Func(
        [BettingMarket],
        [IDL.Vec(Prediction)],
        ['query'],
      ),
    'getPredictionsBySport' : IDL.Func(
        [SportsCategory],
        [IDL.Vec(Prediction)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUpcomingMatches' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantManualPremiumAccess' : IDL.Func([IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'redeemReferralCode' : IDL.Func([IDL.Text], [], []),
    'removeUpcomingMatch' : IDL.Func([IDL.Text], [], []),
    'revokeManualPremiumAccess' : IDL.Func([IDL.Principal], [], []),
    'revokeReferralCode' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCoachingStyle' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setDepthChart' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setInjuryReport' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setNewsFlag' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePrediction' : IDL.Func([Prediction], [], []),
    'updateUserProfileData' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };