/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminPremiumDiagnosis {
  'premiumSource' : PremiumSource,
  'user' : [] | [UserProfile],
}
export type BettingMarket = { 'sameGameParlays' : null } |
  { 'overUnder' : null } |
  { 'alternativeSpreads' : null } |
  { 'pointSpreads' : null } |
  { 'moneyLine' : null } |
  { 'otherMarkets' : string } |
  { 'alternativeOvers' : null };
export type GameId = string;
export interface LiveScore {
  'status' : string,
  'currentPeriod' : string,
  'homeTeam' : string,
  'lastUpdated' : Time,
  'homeScore' : bigint,
  'awayTeam' : string,
  'awayScore' : bigint,
}
export interface Prediction {
  'id' : string,
  'winningProbability' : number,
  'marketValue' : string,
  'createdAt' : Time,
  'juice' : string,
  'sport' : SportsCategory,
  'market' : BettingMarket,
  'matchDate' : Time,
}
export type PremiumSource = { 'stripe' : null } |
  { 'creator' : null } |
  { 'referral' : null } |
  { 'admin' : null } |
  { 'none' : null } |
  { 'manual' : null };
export interface ReferralCodeStatus { 'code' : string, 'validUntil' : Time }
export interface ReferralStatus { 'expiresAt' : Time, 'code' : string }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type SportsCategory = { 'mlb' : null } |
  { 'nba' : null } |
  { 'nfl' : null } |
  { 'nhl' : null } |
  { 'soccer' : null } |
  { 'other' : string } |
  { 'ncaabb' : null } |
  { 'ncaaf' : null };
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionPlan = { 'monthly' : null } |
  { 'yearly' : null };
export interface SubscriptionStatus {
  'expiresAt' : Time,
  'plan' : SubscriptionPlan,
  'stripeSessionId' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'hasManualPremium' : boolean,
  'referral' : [] | [ReferralStatus],
  'subscription' : [] | [SubscriptionStatus],
  'name' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateSubscription' : ActorMethod<[string, SubscriptionPlan], undefined>,
  'addUpcomingMatch' : ActorMethod<[string], undefined>,
  'adminPremiumDiagnosis' : ActorMethod<[Principal], AdminPremiumDiagnosis>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'batchUpdateLiveScores' : ActorMethod<
    [Array<[GameId, LiveScore]>],
    undefined
  >,
  'checkPremiumStatus' : ActorMethod<[], PremiumSource>,
  'checkSubscriptionStatus' : ActorMethod<[], [] | [SubscriptionStatus]>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPrediction' : ActorMethod<[Prediction], undefined>,
  'createReferralCode' : ActorMethod<[string, Time], undefined>,
  'deletePrediction' : ActorMethod<[string], undefined>,
  'getActiveReferralCodes' : ActorMethod<[], Array<ReferralCodeStatus>>,
  'getAllLiveScores' : ActorMethod<[], Array<LiveScore>>,
  'getAllPredictions' : ActorMethod<[], Array<Prediction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoachingStyle' : ActorMethod<[string], [] | [string]>,
  'getDepthChart' : ActorMethod<[string], [] | [string]>,
  'getFinalScores' : ActorMethod<[], Array<LiveScore>>,
  'getGamesInProgress' : ActorMethod<[], Array<LiveScore>>,
  'getInjuryReport' : ActorMethod<[string], [] | [string]>,
  'getLiveMatchesSummary' : ActorMethod<
    [],
    { 'total' : bigint, 'finals' : bigint, 'inProgress' : bigint }
  >,
  'getLiveScore' : ActorMethod<[GameId], [] | [LiveScore]>,
  'getLiveScoresByLeague' : ActorMethod<[string], Array<LiveScore>>,
  'getLiveScoresBySport' : ActorMethod<[SportsCategory], Array<LiveScore>>,
  'getLiveScoresByTeam' : ActorMethod<[string], Array<LiveScore>>,
  'getNewsFlag' : ActorMethod<[string], [] | [string]>,
  'getPrediction' : ActorMethod<[string], [] | [Prediction]>,
  'getPredictionsByDateRange' : ActorMethod<[Time, Time], Array<Prediction>>,
  'getPredictionsByMarket' : ActorMethod<[BettingMarket], Array<Prediction>>,
  'getPredictionsBySport' : ActorMethod<[SportsCategory], Array<Prediction>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUpcomingMatches' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantManualPremiumAccess' : ActorMethod<[Principal], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'redeemReferralCode' : ActorMethod<[string], undefined>,
  'removeFinishedGames' : ActorMethod<[], undefined>,
  'removeLiveScore' : ActorMethod<[GameId], undefined>,
  'removeUpcomingMatch' : ActorMethod<[string], undefined>,
  'revokeManualPremiumAccess' : ActorMethod<[Principal], undefined>,
  'revokeReferralCode' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCoachingStyle' : ActorMethod<[string, string], undefined>,
  'setDepthChart' : ActorMethod<[string, string], undefined>,
  'setInjuryReport' : ActorMethod<[string, string], undefined>,
  'setNewsFlag' : ActorMethod<[string, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateLiveScore' : ActorMethod<[GameId, LiveScore], undefined>,
  'updatePrediction' : ActorMethod<[Prediction], undefined>,
  'updateUserProfileData' : ActorMethod<[string, [] | [string]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];