/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type SportsCategory = {
    __kind__: "mlb";
    mlb: null;
} | {
    __kind__: "nba";
    nba: null;
} | {
    __kind__: "nfl";
    nfl: null;
} | {
    __kind__: "nhl";
    nhl: null;
} | {
    __kind__: "soccer";
    soccer: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "ncaabb";
    ncaabb: null;
} | {
    __kind__: "ncaaf";
    ncaaf: null;
};
export interface ReferralStatus {
    expiresAt: Time;
    code: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface Prediction {
    id: string;
    winningProbability: number;
    marketValue: string;
    createdAt: Time;
    juice: string;
    sport: SportsCategory;
    market: BettingMarket;
    matchDate: Time;
}
export type BettingMarket = {
    __kind__: "sameGameParlays";
    sameGameParlays: null;
} | {
    __kind__: "overUnder";
    overUnder: null;
} | {
    __kind__: "alternativeSpreads";
    alternativeSpreads: null;
} | {
    __kind__: "pointSpreads";
    pointSpreads: null;
} | {
    __kind__: "moneyLine";
    moneyLine: null;
} | {
    __kind__: "otherMarkets";
    otherMarkets: string;
} | {
    __kind__: "alternativeOvers";
    alternativeOvers: null;
};
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface LiveScore {
    status: string;
    currentPeriod: string;
    homeTeam: string;
    lastUpdated: Time;
    homeScore: bigint;
    awayTeam: string;
    awayScore: bigint;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type GameId = string;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface AdminPremiumDiagnosis {
    premiumSource: PremiumSource;
    user?: UserProfile;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface SubscriptionStatus {
    expiresAt: Time;
    plan: SubscriptionPlan;
    stripeSessionId: string;
}
export interface UserProfile {
    hasManualPremium: boolean;
    referral?: ReferralStatus;
    subscription?: SubscriptionStatus;
    name: string;
    email?: string;
}
export interface ReferralCodeStatus {
    code: string;
    validUntil: Time;
}
export enum PremiumSource {
    stripe = "stripe",
    creator = "creator",
    referral = "referral",
    admin = "admin",
    none = "none",
    manual = "manual"
}
export enum SubscriptionPlan {
    monthly = "monthly",
    yearly = "yearly"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateSubscription(sessionId: string, plan: SubscriptionPlan): Promise<void>;
    addUpcomingMatch(matchId: string): Promise<void>;
    adminPremiumDiagnosis(target: Principal): Promise<AdminPremiumDiagnosis>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    batchUpdateLiveScores(scores: Array<[GameId, LiveScore]>): Promise<void>;
    checkPremiumStatus(): Promise<PremiumSource>;
    checkSubscriptionStatus(): Promise<SubscriptionStatus | null>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createPrediction(prediction: Prediction): Promise<void>;
    createReferralCode(code: string, validForNs: Time): Promise<void>;
    deletePrediction(predictionId: string): Promise<void>;
    getActiveReferralCodes(): Promise<Array<ReferralCodeStatus>>;
    getAllLiveScores(): Promise<Array<LiveScore>>;
    getAllPredictions(): Promise<Array<Prediction>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoachingStyle(teamSportKey: string): Promise<string | null>;
    getDepthChart(teamSportKey: string): Promise<string | null>;
    getFinalScores(): Promise<Array<LiveScore>>;
    getGamesInProgress(): Promise<Array<LiveScore>>;
    getInjuryReport(playerTeamKey: string): Promise<string | null>;
    getLiveMatchesSummary(): Promise<{
        total: bigint;
        finals: bigint;
        inProgress: bigint;
    }>;
    getLiveScore(gameId: GameId): Promise<LiveScore | null>;
    getLiveScoresByLeague(_league: string): Promise<Array<LiveScore>>;
    getLiveScoresBySport(_sport: SportsCategory): Promise<Array<LiveScore>>;
    getLiveScoresByTeam(teamName: string): Promise<Array<LiveScore>>;
    getNewsFlag(key: string): Promise<string | null>;
    getPrediction(predictionId: string): Promise<Prediction | null>;
    getPredictionsByDateRange(startTime: Time, endTime: Time): Promise<Array<Prediction>>;
    getPredictionsByMarket(market: BettingMarket): Promise<Array<Prediction>>;
    getPredictionsBySport(sport: SportsCategory): Promise<Array<Prediction>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUpcomingMatches(): Promise<Array<string>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    grantManualPremiumAccess(user: Principal): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    redeemReferralCode(code: string): Promise<void>;
    removeFinishedGames(): Promise<void>;
    removeLiveScore(gameId: GameId): Promise<void>;
    removeUpcomingMatch(matchId: string): Promise<void>;
    revokeManualPremiumAccess(user: Principal): Promise<void>;
    revokeReferralCode(code: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setCoachingStyle(teamSportKey: string, data: string): Promise<void>;
    setDepthChart(teamSportKey: string, data: string): Promise<void>;
    setInjuryReport(playerTeamKey: string, data: string): Promise<void>;
    setNewsFlag(key: string, data: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateLiveScore(gameId: GameId, score: LiveScore): Promise<void>;
    updatePrediction(prediction: Prediction): Promise<void>;
    updateUserProfileData(name: string, email: string | null): Promise<void>;
}
import type { AdminPremiumDiagnosis as _AdminPremiumDiagnosis, BettingMarket as _BettingMarket, LiveScore as _LiveScore, Prediction as _Prediction, PremiumSource as _PremiumSource, ReferralStatus as _ReferralStatus, SportsCategory as _SportsCategory, StripeSessionStatus as _StripeSessionStatus, SubscriptionPlan as _SubscriptionPlan, SubscriptionStatus as _SubscriptionStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateSubscription(arg0: string, arg1: SubscriptionPlan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateSubscription(arg0, to_candid_SubscriptionPlan_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateSubscription(arg0, to_candid_SubscriptionPlan_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addUpcomingMatch(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUpcomingMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUpcomingMatch(arg0);
            return result;
        }
    }
    async adminPremiumDiagnosis(arg0: Principal): Promise<AdminPremiumDiagnosis> {
        if (this.processError) {
            try {
                const result = await this.actor.adminPremiumDiagnosis(arg0);
                return from_candid_AdminPremiumDiagnosis_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminPremiumDiagnosis(arg0);
            return from_candid_AdminPremiumDiagnosis_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async batchUpdateLiveScores(arg0: Array<[GameId, LiveScore]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.batchUpdateLiveScores(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchUpdateLiveScores(arg0);
            return result;
        }
    }
    async checkPremiumStatus(): Promise<PremiumSource> {
        if (this.processError) {
            try {
                const result = await this.actor.checkPremiumStatus();
                return from_candid_PremiumSource_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkPremiumStatus();
            return from_candid_PremiumSource_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkSubscriptionStatus(): Promise<SubscriptionStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkSubscriptionStatus();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkSubscriptionStatus();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createPrediction(arg0: Prediction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPrediction(to_candid_Prediction_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPrediction(to_candid_Prediction_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createReferralCode(arg0: string, arg1: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createReferralCode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReferralCode(arg0, arg1);
            return result;
        }
    }
    async deletePrediction(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePrediction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePrediction(arg0);
            return result;
        }
    }
    async getActiveReferralCodes(): Promise<Array<ReferralCodeStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveReferralCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveReferralCodes();
            return result;
        }
    }
    async getAllLiveScores(): Promise<Array<LiveScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLiveScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLiveScores();
            return result;
        }
    }
    async getAllPredictions(): Promise<Array<Prediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPredictions();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPredictions();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoachingStyle(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoachingStyle(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoachingStyle(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDepthChart(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepthChart(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepthChart(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinalScores(): Promise<Array<LiveScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinalScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinalScores();
            return result;
        }
    }
    async getGamesInProgress(): Promise<Array<LiveScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGamesInProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGamesInProgress();
            return result;
        }
    }
    async getInjuryReport(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInjuryReport(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInjuryReport(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLiveMatchesSummary(): Promise<{
        total: bigint;
        finals: bigint;
        inProgress: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveMatchesSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveMatchesSummary();
            return result;
        }
    }
    async getLiveScore(arg0: GameId): Promise<LiveScore | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveScore(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveScore(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLiveScoresByLeague(arg0: string): Promise<Array<LiveScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveScoresByLeague(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveScoresByLeague(arg0);
            return result;
        }
    }
    async getLiveScoresBySport(arg0: SportsCategory): Promise<Array<LiveScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveScoresBySport(to_candid_SportsCategory_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveScoresBySport(to_candid_SportsCategory_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getLiveScoresByTeam(arg0: string): Promise<Array<LiveScore>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveScoresByTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveScoresByTeam(arg0);
            return result;
        }
    }
    async getNewsFlag(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsFlag(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsFlag(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrediction(arg0: string): Promise<Prediction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrediction(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrediction(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPredictionsByDateRange(arg0: Time, arg1: Time): Promise<Array<Prediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictionsByDateRange(arg0, arg1);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictionsByDateRange(arg0, arg1);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPredictionsByMarket(arg0: BettingMarket): Promise<Array<Prediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictionsByMarket(to_candid_BettingMarket_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictionsByMarket(to_candid_BettingMarket_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPredictionsBySport(arg0: SportsCategory): Promise<Array<Prediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictionsBySport(to_candid_SportsCategory_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictionsBySport(to_candid_SportsCategory_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingMatches(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingMatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingMatches();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantManualPremiumAccess(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantManualPremiumAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantManualPremiumAccess(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async redeemReferralCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemReferralCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemReferralCode(arg0);
            return result;
        }
    }
    async removeFinishedGames(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFinishedGames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFinishedGames();
            return result;
        }
    }
    async removeLiveScore(arg0: GameId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeLiveScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeLiveScore(arg0);
            return result;
        }
    }
    async removeUpcomingMatch(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUpcomingMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUpcomingMatch(arg0);
            return result;
        }
    }
    async revokeManualPremiumAccess(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeManualPremiumAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeManualPremiumAccess(arg0);
            return result;
        }
    }
    async revokeReferralCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeReferralCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeReferralCode(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setCoachingStyle(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCoachingStyle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCoachingStyle(arg0, arg1);
            return result;
        }
    }
    async setDepthChart(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDepthChart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDepthChart(arg0, arg1);
            return result;
        }
    }
    async setInjuryReport(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setInjuryReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setInjuryReport(arg0, arg1);
            return result;
        }
    }
    async setNewsFlag(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setNewsFlag(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNewsFlag(arg0, arg1);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateLiveScore(arg0: GameId, arg1: LiveScore): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLiveScore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLiveScore(arg0, arg1);
            return result;
        }
    }
    async updatePrediction(arg0: Prediction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrediction(to_candid_Prediction_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrediction(to_candid_Prediction_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateUserProfileData(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfileData(arg0, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfileData(arg0, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AdminPremiumDiagnosis_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminPremiumDiagnosis): AdminPremiumDiagnosis {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_BettingMarket_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BettingMarket): BettingMarket {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Prediction_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Prediction): Prediction {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_PremiumSource_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PremiumSource): PremiumSource {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SportsCategory_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SportsCategory): SportsCategory {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionPlan_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionPlan): SubscriptionPlan {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReferralStatus]): ReferralStatus | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionStatus]): SubscriptionStatus | null {
    return value.length === 0 ? null : from_candid_SubscriptionStatus_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LiveScore]): LiveScore | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Prediction]): Prediction | null {
    return value.length === 0 ? null : from_candid_Prediction_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiresAt: _Time;
    plan: _SubscriptionPlan;
    stripeSessionId: string;
}): {
    expiresAt: Time;
    plan: SubscriptionPlan;
    stripeSessionId: string;
} {
    return {
        expiresAt: value.expiresAt,
        plan: from_candid_SubscriptionPlan_n14(_uploadFile, _downloadFile, value.plan),
        stripeSessionId: value.stripeSessionId
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    winningProbability: number;
    marketValue: string;
    createdAt: _Time;
    juice: string;
    sport: _SportsCategory;
    market: _BettingMarket;
    matchDate: _Time;
}): {
    id: string;
    winningProbability: number;
    marketValue: string;
    createdAt: Time;
    juice: string;
    sport: SportsCategory;
    market: BettingMarket;
    matchDate: Time;
} {
    return {
        id: value.id,
        winningProbability: value.winningProbability,
        marketValue: value.marketValue,
        createdAt: value.createdAt,
        juice: value.juice,
        sport: from_candid_SportsCategory_n28(_uploadFile, _downloadFile, value.sport),
        market: from_candid_BettingMarket_n30(_uploadFile, _downloadFile, value.market),
        matchDate: value.matchDate
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premiumSource: _PremiumSource;
    user: [] | [_UserProfile];
}): {
    premiumSource: PremiumSource;
    user?: UserProfile;
} {
    return {
        premiumSource: from_candid_PremiumSource_n5(_uploadFile, _downloadFile, value.premiumSource),
        user: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.user))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasManualPremium: boolean;
    referral: [] | [_ReferralStatus];
    subscription: [] | [_SubscriptionStatus];
    name: string;
    email: [] | [string];
}): {
    hasManualPremium: boolean;
    referral?: ReferralStatus;
    subscription?: SubscriptionStatus;
    name: string;
    email?: string;
} {
    return {
        hasManualPremium: value.hasManualPremium,
        referral: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.referral)),
        subscription: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.subscription)),
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    yearly: null;
}): SubscriptionPlan {
    return "monthly" in value ? SubscriptionPlan.monthly : "yearly" in value ? SubscriptionPlan.yearly : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mlb: null;
} | {
    nba: null;
} | {
    nfl: null;
} | {
    nhl: null;
} | {
    soccer: null;
} | {
    other: string;
} | {
    ncaabb: null;
} | {
    ncaaf: null;
}): {
    __kind__: "mlb";
    mlb: null;
} | {
    __kind__: "nba";
    nba: null;
} | {
    __kind__: "nfl";
    nfl: null;
} | {
    __kind__: "nhl";
    nhl: null;
} | {
    __kind__: "soccer";
    soccer: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "ncaabb";
    ncaabb: null;
} | {
    __kind__: "ncaaf";
    ncaaf: null;
} {
    return "mlb" in value ? {
        __kind__: "mlb",
        mlb: value.mlb
    } : "nba" in value ? {
        __kind__: "nba",
        nba: value.nba
    } : "nfl" in value ? {
        __kind__: "nfl",
        nfl: value.nfl
    } : "nhl" in value ? {
        __kind__: "nhl",
        nhl: value.nhl
    } : "soccer" in value ? {
        __kind__: "soccer",
        soccer: value.soccer
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "ncaabb" in value ? {
        __kind__: "ncaabb",
        ncaabb: value.ncaabb
    } : "ncaaf" in value ? {
        __kind__: "ncaaf",
        ncaaf: value.ncaaf
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sameGameParlays: null;
} | {
    overUnder: null;
} | {
    alternativeSpreads: null;
} | {
    pointSpreads: null;
} | {
    moneyLine: null;
} | {
    otherMarkets: string;
} | {
    alternativeOvers: null;
}): {
    __kind__: "sameGameParlays";
    sameGameParlays: null;
} | {
    __kind__: "overUnder";
    overUnder: null;
} | {
    __kind__: "alternativeSpreads";
    alternativeSpreads: null;
} | {
    __kind__: "pointSpreads";
    pointSpreads: null;
} | {
    __kind__: "moneyLine";
    moneyLine: null;
} | {
    __kind__: "otherMarkets";
    otherMarkets: string;
} | {
    __kind__: "alternativeOvers";
    alternativeOvers: null;
} {
    return "sameGameParlays" in value ? {
        __kind__: "sameGameParlays",
        sameGameParlays: value.sameGameParlays
    } : "overUnder" in value ? {
        __kind__: "overUnder",
        overUnder: value.overUnder
    } : "alternativeSpreads" in value ? {
        __kind__: "alternativeSpreads",
        alternativeSpreads: value.alternativeSpreads
    } : "pointSpreads" in value ? {
        __kind__: "pointSpreads",
        pointSpreads: value.pointSpreads
    } : "moneyLine" in value ? {
        __kind__: "moneyLine",
        moneyLine: value.moneyLine
    } : "otherMarkets" in value ? {
        __kind__: "otherMarkets",
        otherMarkets: value.otherMarkets
    } : "alternativeOvers" in value ? {
        __kind__: "alternativeOvers",
        alternativeOvers: value.alternativeOvers
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n38(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stripe: null;
} | {
    creator: null;
} | {
    referral: null;
} | {
    admin: null;
} | {
    none: null;
} | {
    manual: null;
}): PremiumSource {
    return "stripe" in value ? PremiumSource.stripe : "creator" in value ? PremiumSource.creator : "referral" in value ? PremiumSource.referral : "admin" in value ? PremiumSource.admin : "none" in value ? PremiumSource.none : "manual" in value ? PremiumSource.manual : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Prediction>): Array<Prediction> {
    return value.map((x)=>from_candid_Prediction_n26(_uploadFile, _downloadFile, x));
}
function to_candid_BettingMarket_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BettingMarket): _BettingMarket {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Prediction_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Prediction): _Prediction {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_SportsCategory_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SportsCategory): _SportsCategory {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionPlan_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): _SubscriptionPlan {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    winningProbability: number;
    marketValue: string;
    createdAt: Time;
    juice: string;
    sport: SportsCategory;
    market: BettingMarket;
    matchDate: Time;
}): {
    id: string;
    winningProbability: number;
    marketValue: string;
    createdAt: _Time;
    juice: string;
    sport: _SportsCategory;
    market: _BettingMarket;
    matchDate: _Time;
} {
    return {
        id: value.id,
        winningProbability: value.winningProbability,
        marketValue: value.marketValue,
        createdAt: value.createdAt,
        juice: value.juice,
        sport: to_candid_SportsCategory_n21(_uploadFile, _downloadFile, value.sport),
        market: to_candid_BettingMarket_n23(_uploadFile, _downloadFile, value.market),
        matchDate: value.matchDate
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasManualPremium: boolean;
    referral?: ReferralStatus;
    subscription?: SubscriptionStatus;
    name: string;
    email?: string;
}): {
    hasManualPremium: boolean;
    referral: [] | [_ReferralStatus];
    subscription: [] | [_SubscriptionStatus];
    name: string;
    email: [] | [string];
} {
    return {
        hasManualPremium: value.hasManualPremium,
        referral: value.referral ? candid_some(value.referral) : candid_none(),
        subscription: value.subscription ? candid_some(to_candid_SubscriptionStatus_n41(_uploadFile, _downloadFile, value.subscription)) : candid_none(),
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiresAt: Time;
    plan: SubscriptionPlan;
    stripeSessionId: string;
}): {
    expiresAt: _Time;
    plan: _SubscriptionPlan;
    stripeSessionId: string;
} {
    return {
        expiresAt: value.expiresAt,
        plan: to_candid_SubscriptionPlan_n1(_uploadFile, _downloadFile, value.plan),
        stripeSessionId: value.stripeSessionId
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionPlan): {
    monthly: null;
} | {
    yearly: null;
} {
    return value == SubscriptionPlan.monthly ? {
        monthly: null
    } : value == SubscriptionPlan.yearly ? {
        yearly: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "mlb";
    mlb: null;
} | {
    __kind__: "nba";
    nba: null;
} | {
    __kind__: "nfl";
    nfl: null;
} | {
    __kind__: "nhl";
    nhl: null;
} | {
    __kind__: "soccer";
    soccer: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "ncaabb";
    ncaabb: null;
} | {
    __kind__: "ncaaf";
    ncaaf: null;
}): {
    mlb: null;
} | {
    nba: null;
} | {
    nfl: null;
} | {
    nhl: null;
} | {
    soccer: null;
} | {
    other: string;
} | {
    ncaabb: null;
} | {
    ncaaf: null;
} {
    return value.__kind__ === "mlb" ? {
        mlb: value.mlb
    } : value.__kind__ === "nba" ? {
        nba: value.nba
    } : value.__kind__ === "nfl" ? {
        nfl: value.nfl
    } : value.__kind__ === "nhl" ? {
        nhl: value.nhl
    } : value.__kind__ === "soccer" ? {
        soccer: value.soccer
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "ncaabb" ? {
        ncaabb: value.ncaabb
    } : value.__kind__ === "ncaaf" ? {
        ncaaf: value.ncaaf
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "sameGameParlays";
    sameGameParlays: null;
} | {
    __kind__: "overUnder";
    overUnder: null;
} | {
    __kind__: "alternativeSpreads";
    alternativeSpreads: null;
} | {
    __kind__: "pointSpreads";
    pointSpreads: null;
} | {
    __kind__: "moneyLine";
    moneyLine: null;
} | {
    __kind__: "otherMarkets";
    otherMarkets: string;
} | {
    __kind__: "alternativeOvers";
    alternativeOvers: null;
}): {
    sameGameParlays: null;
} | {
    overUnder: null;
} | {
    alternativeSpreads: null;
} | {
    pointSpreads: null;
} | {
    moneyLine: null;
} | {
    otherMarkets: string;
} | {
    alternativeOvers: null;
} {
    return value.__kind__ === "sameGameParlays" ? {
        sameGameParlays: value.sameGameParlays
    } : value.__kind__ === "overUnder" ? {
        overUnder: value.overUnder
    } : value.__kind__ === "alternativeSpreads" ? {
        alternativeSpreads: value.alternativeSpreads
    } : value.__kind__ === "pointSpreads" ? {
        pointSpreads: value.pointSpreads
    } : value.__kind__ === "moneyLine" ? {
        moneyLine: value.moneyLine
    } : value.__kind__ === "otherMarkets" ? {
        otherMarkets: value.otherMarkets
    } : value.__kind__ === "alternativeOvers" ? {
        alternativeOvers: value.alternativeOvers
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
